spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/logistics}
    username: ${POSTGRES_USER:logistics_user}
    password: ${POSTGRES_PASSWORD:logistics_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
flyway:
  enabled: true
  schemas: logistics
  locations: classpath:db/migration

logging:
  level:
    root: INFO
    com.logistics: DEBUG
