services:
  scylla:
    image: scylladb/scylla
    container_name: scylla
    ports:
      - "9042:9042"
    volumes:
      - scylla-data:/var/lib/scylla
      - ./init-scylla.sh:/docker-entrypoint-initdb.d/init-scylla.sh
    environment:
      - SCYLLA_CLUSTER_NAME=logistics-cluster
      - SCYLLA_SEEDS=scylla
      - SCYLLA_USERNAME=logistics_name
      - SCYLLA_PASSWORD=logistics_password
    healthcheck:
      test: ["CMD", "cqlsh", "-u", "logistics_name", "-p", "logistics_password", "-e"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  scylla-data:
